[package]
name = "minimaxer"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "my_benchmark"
harness = false


[profile.bench]
debug = true

[dependencies]
atomic_float = "1.1.0"
burn = "0.18.0"
log = "0.4.27"
rand = "0.8"
rayon = "1.11.0"
test-log = "0.2.18"
